<a href="https://colab.research.google.com/github/NilsGrossepieper/Deep_Learning_Visual_Data_Assignemnt1/blob/main/assignment_1A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensors

In order to get anything done with deep learning, we need some way to store and manipulate data. 
Therefore, to start, we develop proficiency with the n-dimensional array in PyTorch, which is also called the tensor.

In [1]:
# I import all necessary packages at the beginning
import torch
import numpy as np
import math
import time

### Exercise 1A:
Create in the next code cell a 32-bit floating point torch Tensor of shape `(4,5)` which is filled with square root of 29.

In [2]:
# First I create the tensor and its shape, in the next steps I addapt the tensor 
# to the task
torch_1 = torch.ones((4, 5))
torch_1[:, :] = math.sqrt(29)
torch_1 = torch_1.to(torch.float32)

print(torch_1, torch_1.dtype)

tensor([[5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852]]) torch.float32


### Exercise 1B:

Convert the tensor created in the previous exercise to 64-bit floating point.

In [4]:
# Change the data type
torch_1 = torch_1.to(torch.float64)

print(torch_1.dtype)

torch.float64


### Exercise 2:
Create a tensor `x` (you can give it the shape you want) such that its elements are sampled from a normal distribution of mean 3 and variance 2.

Next, create a tensor `y` having the same shape as `x` such that its elements are sampled from a uniform distribution between -1 and 2. Your code should be robust to the shape of `x` such that if you change the shape of `t`, the shape of your `y` should adapt!

In [8]:
# First I set up the shape for x and y, the I create x and y respectively 
x_shape = (3, 4)
x = torch.normal(mean = 3, std = 4, size = x_shape)
# since std^2=var and 2^2=4 I can also write the distribution this way
y = torch.empty_like(x).uniform_(-1, 2)

print(x)
print(y)

tensor([[ 2.0012,  1.3123,  9.4443,  6.6869],
        [ 1.8976,  1.3646,  5.4515,  3.0240],
        [ 2.6429,  5.1444, -5.3690,  4.4211]])
tensor([[ 1.7811, -0.1711,  1.3829,  1.2669],
        [-0.5189,  1.6116,  0.5296, -0.4119],
        [ 1.0384, -0.4832,  0.8416,  0.1425]])


### Exercise 3:

Run `A / A.sum(axis=1)` for the following tensor A and see what happens. Can you analyze the reason? Create a text cell to provide your answer.

In [9]:
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)

# First I take a look at A, A.sum(axis=1) and A / A.sum(axis=1)
B = A.sum(axis=1)
print(A, A.shape)
print(B, B.shape)
print(B.reshape(4, 1), B.shape)
#print(A / B)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]) torch.Size([4, 5])
tensor([10., 35., 60., 85.]) torch.Size([4])
tensor([[10.],
        [35.],
        [60.],
        [85.]]) torch.Size([4])


When you run the last line of code you get the following error message: "The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1" The proble is that the tensor A is a two dimensional tensor, while the tensor B (A.sum(axis=1)) is only a single dimensional tensor. Since this dimension is not a singleton dimension (size greater than 1), the tensors can not be broadcasted to match their sizes for this dimension. Since the two tensors have not the same dimensions we can not perform the computation A / A.sum(axis=1). You can prefent this error message when you adjust the dimensions of the two elements:

In [11]:
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)
A / A.sum(axis=1, keepdim=True)

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571],
        [0.1667, 0.1833, 0.2000, 0.2167, 0.2333],
        [0.1765, 0.1882, 0.2000, 0.2118, 0.2235]])

### Exercise 4:

As with an ordinary Python array, we can access the length of a tensor by calling Python’s built-in `len()` function.

In [12]:
x = torch.arange(4)
len(x)

4

We now define a tensor `X` of shape `(2, 3, 4)` . What is the output of `len(X)`? Can you analyse the reason for the output? Create a text cell to provide your answer.

In [13]:
X = torch.arange(24).reshape(2, 3, 4)
len(X)

2

The length of a tensor refers to the number of elements in the first dimension. In this case our tensor has 2 elements in the first dimension, therefore we get the result for len(x) as 2. The length of a tensor only refers to its first element, on the otherside you have the size of the tensor which is in our case 2x3x4=24.

### Exercise 5:

We have seen examples of PyTorch `Tensor` broadcasting.

In [14]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(5)
a.shape, b.shape
print(a, b)

tensor([[0],
        [1],
        [2]]) tensor([0, 1, 2, 3, 4])


In [ ]:
a + b


tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

Replace the two tensors in the broadcasting mechanism with different shapes of 3 or 4-dimensional tensors. For example `a = torch.empty(5,2,4,1)`,
`b = torch.empty(3,1,1)`. Is the result the same as expected? Analyse the results. Come up with 3D or 4D tensors with different sizes at each dimension. Can you come up with the rules with examples which are required for Tensor broadcasting to work? Creat a text block to provide your analysis.

In [15]:
a = torch.empty(5,2,4,1)
b = torch.empty(3,1,1)
# a + b
# The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

The result of the addition of a+b is an error message. Since there are basically three main rules for tensor broadcasting:
1.) When you have two tensors with the same amount of dimensions, then the magnitudes of every dimension has to be the same or it has to be one in at least one of the two tensors. The tensors (2, 1, 3) and (1, 2, 3) can be extended, but the tensors (2, 3, 3) and (3, 3, 3) can not be extended, althoug they differ only in one dimension.


In [16]:
# 1.) Rule
t1_r1 = torch.rand(2, 1, 3)
t2_r1 = torch.rand(1, 2, 3)
t3_r1 = torch.rand(2, 3, 3)
t4_r1 = torch.rand(3, 3, 3)

t1_r1 + t2_r1
# t3_r1 + t4_r1
# The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

# This combination is also possible: 
# t1_r1 + t3_r1

tensor([[[1.0443, 1.1988, 0.2744],
         [0.9846, 1.3001, 0.5141]],

        [[1.1166, 1.1896, 1.1557],
         [1.0569, 1.2910, 1.3955]]])

2.) When two tensors have different numbers of dimensions, then the tensor with fewer dimensions is expanded with the size of 1 to increase the number of dimensions to the same number as the biger tensor.For exaple the the tensors (2, 3, 4) and (3, 4)  can be expanded by one dimension so they become the tensors (2, 3, 4) and (2, 3, 4), now we can add up the tow tensors.

In [17]:
# 2.) Rule
t1_r2 = torch.rand(2, 3, 4)
t2_r2 = torch.rand(3, 4)

t1_r2 + t2_r2

tensor([[[1.5630, 0.1679, 1.3697, 0.6004],
         [1.7121, 1.5562, 0.4634, 0.2782],
         [1.0194, 1.4151, 1.6721, 0.7430]],

        [[1.5553, 0.7381, 1.6876, 0.9418],
         [1.5257, 0.8665, 0.5724, 0.9973],
         [0.9505, 1.2825, 1.6990, 1.0011]]])

3.) When a tensor of size 1 is in a certain dimension, it can get expanded along its dimensions to the size of the other tensor. This example is similar to the first one, the tensors (2, 1, 4) and (2, 2, 4) can be combined when the first tensor gets expanded to (2, 2, 4).

In [18]:
# 3.) Rule
t1_r3 = torch.rand(2, 1, 4)
t2_r3 = torch.rand(2, 2, 4)

t1_r3 + t2_r3

tensor([[[0.6971, 1.3166, 1.1337, 1.3806],
         [1.1185, 0.5080, 1.4235, 1.4717]],

        [[1.5727, 1.3246, 0.1998, 0.9530],
         [1.5949, 1.6226, 1.1201, 0.9108]]])

### Exercise 6:

Create a one dimensional tensor `x` containing the numbers `0` to `23` in order.
Reshape x in the next code cell to create the following tensor:

```
tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
             [ 4,  5,  6,  7, 16, 17, 18, 19],
             [ 8,  9, 10, 11, 20, 21, 22, 23]])
```





In [59]:
# Create a one dimensional tensor with the number 0 to 23 and reshape the tensor
tensor_6 = torch.arange(24)
print(tensor_6.shape)
tensor_6 = tensor_6.reshape(3, -1)

# Reorder the numbers by first creating subtensors which have to replace the old 
# order
sub_1 = tensor_6[0, 0:4]
sub_2 = tensor_6[0, 4:8]
sub_3 = tensor_6[1, 0:4]
sub_4 = tensor_6[1, 4:8]
sub_5 = tensor_6[2, 0:4]
sub_6 = tensor_6[2, 4:8]
print(sub_1, sub_1.shape)

# Plug in the subtensors
row_1 = torch.cat((sub_1, sub_4), dim=-1)
row_2 = torch.cat((sub_2, sub_5), dim=-1)
row_3 = torch.cat((sub_3, sub_6), dim=-1)
final = torch.cat((row_1, row_2, row_3), dim = 0)
final = final.reshape(3, -1)

# You can do the task more efficient (the first reshape is not necessary), but I
# only found out at the end that I had to reorder the sub tensors so that is the
# reason why I used this long approach
print(final)

torch.Size([24])
tensor([0, 1, 2, 3]) torch.Size([4])
tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])


### Exercise 7:

A one-hot vector for an integer $n$ is a vector that has a one in its $n$th slot, and zeros in all other slots. One-hot vectors are used to represent categorical variables in machine learning.

Implement a function in the following code cell that creates a 2D PyTorch tensor of one-hot row vectors from a list of Python integers.

For example, given a list `[1, 2, 3, 3]` of integers, your function should produce the 2D tensor:

```
[[0 1 0 0],
 [0 0 1 0],
 [0 0 0 1],
 [0 0 0 1]]
```



In [63]:
def one_hot_vector(x):
  # Get the shape of the tensor
  x_dimension = len(x)
  y_dimension = max(x)
  raw_tensor = torch.zeros((x_dimension, y_dimension + 1)) 

  # Implement the 1s into the right postion
  for i in range(0, len(x)):
    raw_tensor[i, x[i]] = 1
  
  # In the example it looks like that we only have integers in our tensor so 
  # I change the data type to int64
  final_tensor = raw_tensor.to(torch.int64)

  return(final_tensor)

# test your function 
x = [1, 2, 3, 3, -1, 0, 8, -2, 1]
print(one_hot_vector(x))

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0]])


### Exercise 8:

Use the GPU to accelerate multiplication of the following large 2D PyTorch tensors. First perform the multiplication on CPU. Next perform the computation on GPU. Compare the time required for mulplication on CPU vs GPU.

In [70]:
x = torch.rand(1024, 4096)
y = torch.rand(4096, 8192)

# Get the device
print('x device:', x.device)
print('y device:', y.device)

# 1. Do the multiplication on the CPU:
start_cpu = time.time()
cpu_result= torch.mm(x, y)
end_cpu = time.time()
duration_cpu = end_cpu - start_cpu

# Change the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x_gpu = x.to(device)
y_gpu = y.to(device)
print('y device:', x_gpu.device)
print('y device:', y_gpu.device)

# 2. Do the multiplication on the GPU:
start_gpu = time.time()
gpu_result= torch.mm(x_gpu, y_gpu)
gpu_result = gpu_result.to("cpu")
end_gpu = time.time()
duration_gpu = end_gpu - start_gpu

# The result for CPU multiplication:
print(duration_cpu)

# The result for GPU multiplication:
print(duration_gpu)

# The GPU calculation is faster than the CPU calculation.

x device: cpu
y device: cpu
y device: cuda:0
y device: cuda:0
1.05070161819458
0.04694724082946777


### Exercise 9: 

Create a function to compute the number of negative values in a tensor.
Your code should not use any loops. After implementing the function, test your function with input PyTorch tensors of different shapes.

In [71]:
def negative_value_count(x):
  # Count the negative values 
  n_neg_values = torch.sum(x < 0).item()
  return(n_neg_values)

test_1 = torch.arange(8)
test_2 = torch.arange(-2, 4)
test_3 = torch.ones(3,4)
test_4 = torch.full((3, 4), -1)

# All the tests give me the correct answers 
print(negative_value_count(test_1))
print(negative_value_count(test_2))
print(negative_value_count(test_3))
print(negative_value_count(test_4))

0
2
0
12


### Exercise 10:

Create a function which returns the copy of the input tensor but with maximum value along each column set to `-1`.

  For example:

```
 x = torch.tensor([[
        [12, 21, 1],
        [ 4,  7,  20]
      ]])
```


  Then `y = negative_max_column(x)` should be:
 
  ```
torch.tensor([
    [-1, -1, 1],
    [2,  5,  -1]
  ])
```


Your code should not use any loops. Test your function with some examples.

In [72]:
def negative_max_column(x):

  # Get the index of the highest number in each row and replace it with -1
  x[x == torch.max(x, dim=1, keepdim=True)[0]] = -1

  # Return the final Tensor
  return(x) 

# Test the function
x = torch.tensor([
        [-5, 6, 0],
        [20, 8, 100],
        [4, 4, 1]
      ])
t1_r2 = torch.rand(2, 3, 4)
print(negative_max_column(t1_r2))

tensor([[[ 0.6370,  0.3068,  0.5301,  0.3459],
         [-1.0000,  0.1440, -1.0000, -1.0000],
         [ 0.1061, -1.0000,  0.5538,  0.4553]],

        [[-1.0000,  0.3920,  0.2897,  0.2165],
         [ 0.0055,  0.3043, -1.0000, -1.0000],
         [ 0.2617, -1.0000,  0.2507,  0.6132]]])


### Exercise 11:

Write a function to subtract the mean of each row from a 2D tensor. Your code should not use any loops. Test your function with some examples.

In [73]:
def subtract_row_mean(x):

  # Convert the tensor input into torch.float32
  x = x.to(torch.float32)

  # Get the mean
  means = torch.mean(x, dim=1, keepdim=True)
  result = x - means

  # Return the results
  return result

# Test the function
x = torch.tensor([
        [3, 3, 6],
        [50, 0, 100],
        [4, 4, 1]
      ])
subtract_row_mean(x)

tensor([[ -1.,  -1.,   2.],
        [  0., -50.,  50.],
        [  1.,   1.,  -2.]])

### Exercise 12:

Feed a tensor with 3 or more dimensions to the `linalg.norm` function and observe its output. What does this function compute for tensors of arbitrary shape? Explain in a block below.

In [75]:
test_tensor_1 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
test_tensor_2 = torch.tensor([[[2], [3], [4]]])

test_1 = np.linalg.norm(test_tensor_1)
test_2 = np.linalg.norm(test_tensor_2)

print(test_1, test_2)

16.881943016134134 5.385164807134504


The function linalg.norm gives you the norm of the tensor. For the test_tensor_2 you can also compute it by hand by the following formular:

In [76]:
norm_tensor_2 = math.sqrt(2**2 + 3**2 + 4**2)

print(norm_tensor_2)

5.385164807134504


### Exercise 13: 

Implement a function that takes in two $2 \mathrm{D}$ tensors $A$ and $B$ and returns the column sum of A multiplied by the sum of all the elmements of $\boldsymbol{B}$, i.e., a scalar, e.g.,
If $A=\left[\begin{array}{ll}1 & 1 \\ 1 & 1\end{array}\right]$ and $B=\left[\begin{array}{lll}1 & 2 & 3 \\ 1 & 2 & 3\end{array}\right]$ then $O u t=\left[\begin{array}{ll}2 & 2\end{array}\right] \cdot 12=\left[\begin{array}{ll}24 & 24\end{array}\right]$

In [77]:
def calculating(tens_1, tens_2):
  col_sum = tens_1.sum(axis=0)
  all_sum = tens_2.sum()
  result = col_sum * all_sum
  return result

# Testing
tens_1 = torch.tensor([[1, 1], [1, 1]])
tens_2 = torch.tensor([[1, 2, 3], [1, 2, 3]])
print(calculating(tens_1, tens_2))

tensor([24, 24])


### Exercise 14:

Implement a function that takes in a square matrix $A$ and returns a $2 D$ tensor consisting of a flattened $A$ with the index of each element appended to this tensor in the row dimension, e.g.,
If $A=\left[\begin{array}{cc}2 & 3 \\ -1 & 10\end{array}\right]$ then $O u t=\left[\begin{array}{cc}0 & 2 \\ 1 & 3 \\ 2 & -1 \\ 3 & 10\end{array}\right]$

In [78]:
def flatting(tens):
  # Create a new empty flat tensor
  length = tens.size(0) * tens.size(1)
  flat_tensor = torch.zeros(length, 2)

  # Reshape the input tensor
  new_tensor = tens.reshape(-1, 1)

  # Fill the flat_tensor with the right numbers
  for i in range(0, len(new_tensor)):
    flat_tensor[i, 0] = i
    flat_tensor[i, 1] = new_tensor[i]

  # Return the flat tensor
  return flat_tensor

# Test the function
tens_test = torch.tensor([[2, 3, 4], [1, 2, 0]])
print(flatting(tens_test))

tensor([[0., 2.],
        [1., 3.],
        [2., 4.],
        [3., 1.],
        [4., 2.],
        [5., 0.]])


### Exercise 15:

Implement a function that takes in two $2 D$ tensors $A$ and $B$. If the shapes allow it, this function returns the elementwise sum of $A$-shaped $B$, and $B$; else this function returns a 1D tensor that is the concatenation of the two tensors, e.g.,
If $A=\left[\begin{array}{cc}1 & -1 \\ -1 & 3\end{array}\right]$ and $B=\left[\begin{array}{llll}2 & 3 & 0 & 2\end{array}\right]$ then $O u t=\left[\begin{array}{cc}3 & 2 \\ -1 & 5\end{array}\right]$
If $A=\left[\begin{array}{cc}1 & -1 \\ -1 & 3\end{array}\right]$ and $B=\left[\begin{array}{ccc}2 & 3 & 0\end{array}\right]$ then $O u t=\left[\begin{array}{ccccccc}1 & -1 & -1 & 3 & 2 & 3 & 0\end{array}\right]$

In [79]:
def adding_tensors(tens_a, tens_b):

  # Check if elementwise sum is possible
  a_shape = tens_a.shape[0] * tens_a.shape[1]
  new_shape_x = tens_a.shape[0]
  new_shape_y = tens_a.shape[1]
  b_shape = tens_b.shape[0] * tens_b.shape[1]
  total_elements = tens_a.numel() + tens_b.numel()

  # First we look at the case where can sum up the tensors
  if a_shape == b_shape:
    new_tens_a = tens_a.reshape(-1, 1)
    new_tens_b = tens_b.reshape(-1, 1)
    tens_sum = torch.zeros_like(new_tens_a)

    # Fill in the new sum tensor
    for i in range(0, len(tens_sum)):
      tens_sum[i, 0] = new_tens_a[i, 0] + new_tens_b[i, 0]

    # Reshape the sum tensor into the
    final_tensor = tens_sum.view(new_shape_x, new_shape_y)

    # Return the final tensor
    return final_tensor 

  # Now we look at the case where we can not sum up the tensors
  else:
    tens_concat = torch.zeros(1, total_elements)
    new_tens_a = tens_a.reshape(-1, 1)
    new_tens_b = tens_b.reshape(-1, 1)

    # Fill in the concated tensor
    for i in range(0, len(new_tens_a)):
      tens_concat[0, i] = new_tens_a[i, 0]

    # Fille the rest of the tensor
    for j in range(0, len(new_tens_b)):
      tens_concat[0, j+len(new_tens_a)] = new_tens_b[j, 0]

    # Return the concat tensor
    return tens_concat
    # You could have done this moreeasily mwith the torch.cat function but first
    # fuoond this function for the next exercise 16 

# Testing
tens_a = torch.tensor([[1, -1, 0], [-1, 3, 8]])
tens_b1 = torch.tensor([[2, 3, 0, 2, 6, 1]])
tens_b2 = torch.tensor([[2, 3, 0, 2, 6]])
print(adding_tensors(tens_a, tens_b1))
print(adding_tensors(tens_a, tens_b2))

tensor([[3, 2, 0],
        [1, 9, 9]])
tensor([[ 1., -1.,  0., -1.,  3.,  8.,  2.,  3.,  0.,  2.,  6.]])


### Exercise 16:

You are given a tensor `samples` with 12 sequences of length 15. Adapt the code below to add a `new_sample` to `samples` tensor.



In [80]:
samples = torch.randn(size=(12, 15))
new_sample = torch.randn(size=(15,))

# Have a look at the shapes of the tensors
print(samples.shape)
print(new_sample.shape)

# Add a dimension to the second tensor
new_sample = new_sample.unsqueeze(0)
print(new_sample.shape)

# Now we can simply add the second tensor to the first one
samples = torch.cat((samples, new_sample), dim=0)
print(samples)
print(samples.shape)

torch.Size([12, 15])
torch.Size([15])
torch.Size([1, 15])
tensor([[ 7.3872e-01,  2.3552e-01,  1.0543e+00, -1.0504e+00, -2.1557e+00,
         -1.3800e-01,  2.3296e+00, -7.3122e-01,  1.4418e+00, -4.1030e-01,
         -1.6334e+00,  1.3518e+00, -8.8716e-01,  6.6167e-01,  2.4278e+00],
        [-1.1329e+00, -9.3975e-01,  1.0207e+00,  6.2327e-01, -7.7920e-02,
          5.6054e-02,  4.4055e-01,  2.0526e-01, -2.2352e+00,  1.4284e+00,
          1.1027e+00, -7.7847e-01,  1.3495e+00,  1.1413e+00,  2.8219e-01],
        [ 9.0616e-02,  1.1563e+00, -4.2676e-01, -6.2902e-01, -1.0432e+00,
          2.5344e-02,  2.0706e+00,  5.2312e-01, -3.3070e-01, -2.3625e-01,
          7.2384e-01, -1.1246e+00,  1.0369e+00, -2.7379e+00, -5.8322e-01],
        [ 2.2135e+00, -1.5929e+00,  7.0380e-01,  7.4870e-01,  4.0565e-01,
         -5.2897e-01, -3.5793e-01,  1.2909e+00, -2.4296e-01,  2.9967e+00,
         -9.8969e-02,  1.1620e+00, -1.7453e-01, -1.4380e-01, -6.5833e-02],
        [ 2.3621e-01, -5.0877e-01,  1.9775e+00, -5

### Exercise 17:

Suppose you have a tensor `images_tensor` containing  a batch of `n_batch` number of images of resolution: 30x30 pixels. `images_tensor` is thus of shape `(n_batch, 1, 30, 30)`

Write a function `flatten_images` that convert `images_tensor` into a tensor containing flattened images (i.e. a tensor of shape: `(n_batch, 1*30*30)`.

In [82]:
# At first I create an examle tensor images_tensor with n_batch = 5
n_batch = 5
images_tensor = torch.randn(n_batch, 1, 30, 30)

# Have a look at the example tensor
#print(images_tensor, images_tensor.shape)

# write the function flatten_images
def flatten_images(im):

  # Get the number of batches
  number_batches = images_tensor.shape[0]

  # Get the size of the second dimension, all pixels per batch in one row
  number_pixels = images_tensor.shape[1] * images_tensor.shape[2] * images_tensor.shape[3]

  # Use the view method to transform the tensor
  flatten_tensor = images_tensor.view(number_batches, number_pixels)

  # Now every picture has its own row 
  return flatten_tensor

# Test the function
print(flatten_images(images_tensor), flatten_images(images_tensor).shape)

tensor([[-1.9963, -1.0539,  1.1016,  ...,  1.1888,  0.7153, -0.2652],
        [-0.4327,  0.4803, -0.1825,  ...,  0.2880, -0.4013, -0.0792],
        [ 1.0705, -1.3218, -0.6981,  ..., -1.3065, -0.7787,  1.0327],
        [-0.2615, -1.6786,  0.8539,  ...,  0.0752,  1.5498,  0.4356],
        [ 0.6643,  0.8476,  0.2236,  ..., -0.4234,  1.1771, -0.3973]]) torch.Size([5, 900])
